import { useEffect, useState } from 'react'
import { busbarSizing, conductors, conduitSizing, egcSizing, formatHorsepower, gecSizing, generalSizing, groundingConductorSizes, hvacSizing, lightingOccupancies, lightingSizing, lightingSizingBySystem, loadConversion, motorFlcFromHp, motorHorsepowers, motorSizing, motorVoltageOptions, motorVoltages, powerFactorCorrection, singleMotorFlcFromHp, singleMotorHorsepowers, singleMotorVoltages, tableMotorVoltage, transformerSizing, voltageDrop, type Electrode, type LightingOccupancy, type LightingUnit, type Material, type MotorPhase, type MotorType, type Result } from './calculations'
import { referenceTables } from './referenceTables'

type Tool = 'general' | 'motor' | 'hvac' | 'ground' | 'gec' | 'conduit' | 'drop' | 'transformer' | 'load' | 'busbar' | 'pfc' | 'lighting' | 'tables'
const tools: { id: Tool; label: string; group: string; mark: string }[] = [
  { id: 'general', label: 'Conductor & OCPD', group: 'Circuit sizing', mark: '01' }, { id: 'motor', label: 'Motor branch circuit', group: 'Circuit sizing', mark: '02' }, { id: 'hvac', label: 'HVAC nameplate', group: 'Circuit sizing', mark: '03' }, { id: 'busbar', label: 'Busbar quick check', group: 'Circuit sizing', mark: '04' },
  { id: 'ground', label: 'Equipment ground', group: 'Grounding', mark: '05' }, { id: 'gec', label: 'Grounding electrode', group: 'Grounding', mark: '06' }, { id: 'conduit', label: 'Conduit fill', group: 'Raceway', mark: '07' }, { id: 'drop', label: 'Voltage drop', group: 'Design checks', mark: '08' }, { id: 'transformer', label: 'Transformer', group: 'Design checks', mark: '09' }, { id: 'load', label: 'Load conversion', group: 'Design checks', mark: '10' }, { id: 'pfc', label: 'Power factor correction', group: 'Design checks', mark: '11' }, { id: 'lighting', label: 'Lighting estimate', group: 'Design checks', mark: '12' },
  { id: 'tables', label: 'NEC tables', group: 'Reference', mark: '13' },
]
const titles: Record<Tool, [string, string]> = {
  general: ['Conductor + OCPD', 'Translate a design load into a conductor and standard overcurrent device.'], motor: ['Motor branch circuit', 'Use FLA/FLC for an Article 430 quick check.'], hvac: ['HVAC nameplate', 'Listed MCA and MOCP are the source of truth for HVAC equipment.'], busbar: ['Busbar quick check', 'Compare a required load with common listed bus ratings and a conservative bar-area estimate.'], ground: ['Equipment grounding conductor', 'Size the EGC from the upstream protective device.'], gec: ['Grounding electrode conductor', 'Size a GEC from the service conductors and electrode connection.'], conduit: ['Conduit fill', 'Find the smallest common raceway for a mixed conductor set.'], drop: ['Voltage drop', 'Optional design check using a resistance-based estimate.'], transformer: ['Transformer quick check', 'Get primary and secondary current targets from kVA.'], load: ['Load conversion', 'Convert watts, VA, or kVA into a working amp value.'], pfc: ['Power factor correction', 'Estimate capacitive kVAr required to reach a target lagging power factor.'], lighting: ['Lighting estimate', 'Estimate a luminaire count from room area, occupancy target, and luminaire output.'], tables: ['NEC reference tables', ''],
}
const voltages = [120, 208, 240, 277, 480, 600]
const materials: { value: Material; label: string }[] = [{ value: 'copper', label: 'Copper' }, { value: 'aluminum', label: 'Aluminum' }]
const field = (label: string, node: React.ReactNode, hint?: string) => <label className="field"><span>{label}</span>{node}{hint && <small>{hint}</small>}</label>
const number = (value: string, set: (value: string) => void, min = 0, step: string | number = 'any') => <input type="number" min={min} step={step} value={value} onChange={event => set(event.target.value)} />
const select = (value: string | number, set: (value: string) => void, values: (string | number)[]) => <select value={value} onChange={event => set(event.target.value)}>{values.map(item => <option key={item} value={item}>{item}</option>)}</select>

function ResultCard({ result }: { result: Result | null }) {
  if (!result) return <section className="result empty"><div className="bolt">∿</div><h2>Ready when you are</h2><p>Enter the design values, then run a quick check. Every output keeps its assumptions and code trail visible.</p></section>
  return <section className="result"><p className="eyebrow">{result.title}</p><h2>{result.primary}</h2><dl>{result.rows.map(([key, item]) => <div key={key}><dt>{key}</dt><dd>{item}</dd></div>)}</dl><div className="result-notes">{result.notes.map(note => <p key={note}>{note}</p>)}</div><div className="citations">{result.citations.map(citation => <span key={citation}>{citation}</span>)}</div></section>
}

function ElectricalInputs({ material, setMaterial, terminal, setTerminal, insulation, setInsulation, ambient, setAmbient, ccc, setCcc }: { material: Material; setMaterial: (value: Material) => void; terminal: string; setTerminal: (value: string) => void; insulation: string; setInsulation: (value: string) => void; ambient: string; setAmbient: (value: string) => void; ccc: string; setCcc: (value: string) => void }) {
  return <div className="input-grid">{field('Conductor material', select(material, value => setMaterial(value as Material), materials.map(item => item.value)))}{field('Terminal rating', select(terminal, setTerminal, [60, 75]))}{field('Insulation rating', select(insulation, setInsulation, [60, 75, 90]))}{field('Ambient temperature', select(ambient, setAmbient, [30, 40, 50, 60]))}{field('Current-carrying conductors', select(ccc, setCcc, [3, 4, 5, 6, 7, 8, 9, 12, 20, 30, 40]))}</div>
}

function Calculator({ active, onResult }: { active: Tool; onResult: (result: Result) => void }) {
  const [material, setMaterial] = useState<Material>('copper'); const [terminal, setTerminal] = useState('75'); const [insulation, setInsulation] = useState('90'); const [ambient, setAmbient] = useState('30'); const [ccc, setCcc] = useState('3')
  const [amps, setAmps] = useState('60'); const [continuous, setContinuous] = useState(true); const [generalMode,setGeneralMode] = useState('Load current'); const [apparentPower,setApparentPower] = useState('10000'); const [powerUnit,setPowerUnit] = useState<'VA'|'kVA'>('VA'); const [generalVoltage,setGeneralVoltage] = useState('208'); const [generalPhase,setGeneralPhase] = useState('3'); const [generalPoles,setGeneralPoles] = useState('3')
  const standard = { material, setMaterial, terminal, setTerminal, insulation, setInsulation, ambient, setAmbient, ccc, setCcc }
  const runGeneral = () => { const va = +apparentPower * (powerUnit === 'kVA' ? 1000 : 1); const phase = +generalPhase as 1 | 3; const ampsFromPower = va / (+generalVoltage * (phase === 3 ? Math.sqrt(3) : 1)); onResult(generalSizing({ amps: generalMode === 'Load current' ? +amps : ampsFromPower, continuous, material, terminal: +terminal, insulation: +insulation, ambient: +ambient, ccc: +ccc, voltage:+generalVoltage, phase, poles:+generalPoles, apparentVa: generalMode === 'Apparent power' ? va : undefined })) }
  if (active === 'general') return <><div className="input-grid">{field('Input path',select(generalMode,setGeneralMode,['Load current','Apparent power']))}{generalMode === 'Load current' ? field('Load current',number(amps,setAmps), 'Amperes') : <>{field('Load apparent power',number(apparentPower,setApparentPower), 'Nameplate or calculated load')}{field('Power unit',select(powerUnit,value=>setPowerUnit(value as 'VA'|'kVA'),['VA','kVA']))}</>}{field('System voltage',select(generalVoltage,setGeneralVoltage,voltages))}{field('Phase',select(generalPhase,setGeneralPhase,[1,3]))}{field('Circuit poles',select(generalPoles,setGeneralPoles,[1,2,3]))}<label className="switch checkbox-field"><input type="checkbox" checked={continuous} onChange={event => setContinuous(event.target.checked)} /><span>Continuous load</span></label></div><ElectricalInputs {...standard} /><button className="run" onClick={runGeneral}>Calculate conductor + OCPD <b>→</b></button></>
  if (active === 'motor') return <MotorForm standard={standard} onResult={onResult} />
  if (active === 'hvac') return <HvacForm standard={standard} onResult={onResult} />
  if (active === 'busbar') return <BusbarForm onResult={onResult} />
  if (active === 'ground') return <GroundForm onResult={onResult} />
  if (active === 'gec') return <GecForm onResult={onResult} />
  if (active === 'conduit') return <ConduitForm onResult={onResult} />
  if (active === 'drop') return <DropForm onResult={onResult} />
  if (active === 'transformer') return <TransformerForm onResult={onResult} />
  if (active === 'pfc') return <PowerFactorForm onResult={onResult} />
  if (active === 'lighting') return <LightingSystemForm onResult={onResult} />
  return <LoadForm onResult={onResult} />
}

function MotorForm({ standard, onResult }: { standard: Parameters<typeof ElectricalInputs>[0]; onResult: (result: Result) => void }) {
  const [mode,setMode]=useState('FLA entry'),[fla,setFla]=useState('16.7'),[hp,setHp]=useState('5'),[voltage,setVoltage]=useState('208'),[phase,setPhase]=useState<MotorPhase>(3),[poles,setPoles]=useState('3'),[type,setType]=useState<MotorType>('squirrel-cage'),[fuse,setFuse]=useState(false)
  const lookupTypes: MotorType[] = ['squirrel-cage','wound-rotor','synchronous']
  const availableHorsepowers = phase === 1 ? singleMotorHorsepowers() : motorHorsepowers(type)
  const availableVoltages = motorVoltageOptions(+hp,type,phase)
  const manualVoltages = phase === 1 ? [115,120,200,208,230,240] : [115,120,200,208,230,240,460,575,2300]
  const resetLookup = (nextPhase: MotorPhase, nextType: MotorType) => { const nextHp = nextPhase === 1 ? singleMotorHorsepowers()[0] : motorHorsepowers(nextType)[0]; const nextVoltage = motorVoltageOptions(nextHp,nextType,nextPhase)[0].systemVoltage; setHp(String(nextHp)); setVoltage(String(nextVoltage)) }
  const setMotorPhase = (next: MotorPhase) => { setPhase(next); if(next === 1) setType('squirrel-cage'); if(mode === 'HP lookup') resetLookup(next,next === 1 ? 'squirrel-cage' : type) }
  const setMotorType = (next: MotorType) => { setType(next); if (mode === 'HP lookup') { const nextHp = motorHorsepowers(next)[0]; setHp(String(nextHp)); setVoltage(String(motorVoltageOptions(nextHp,next,3)[0].systemVoltage)) } }
  const setLookupHp = (next: string) => { setHp(next); setVoltage(String(motorVoltageOptions(+next,type,phase)[0].systemVoltage)) }
  const flc = mode === 'HP lookup' ? (phase === 1 ? singleMotorFlcFromHp(+hp,tableMotorVoltage(+voltage)) : motorFlcFromHp(+hp,tableMotorVoltage(+voltage),type)) ?? 0 : +fla
  return <><div className="input-grid">{field('Input path',select(mode,next=>{ setMode(next); if(next === 'HP lookup') { const nextType = type === 'dc' ? 'squirrel-cage' : type; setType(nextType); resetLookup(phase,nextType) } },['FLA entry','HP lookup']))}{field('Phase',<select value={phase} onChange={event=>setMotorPhase(+event.target.value as MotorPhase)}><option value="1">Single-phase</option><option value="3">Three-phase</option></select>)}{mode === 'HP lookup' ? <>{field('Horsepower',<select value={hp} onChange={event=>setLookupHp(event.target.value)}>{availableHorsepowers.map(item=><option key={item} value={item}>{formatHorsepower(item)}</option>)}</select>)}{field(`${phase}-phase voltage`,<select value={voltage} onChange={event=>setVoltage(event.target.value)}>{availableVoltages.map(option=><option key={option.systemVoltage} value={option.systemVoltage}>{option.label}</option>)}</select>)}</> : <>{field('Motor FLA / FLC',number(fla,setFla), 'Amperes')}{field(`${phase}-phase voltage`,select(voltage,setVoltage,manualVoltages))}</>}{field('Circuit poles',select(poles,setPoles,[1,2,3]))}{phase === 3 && field('Motor type',<select value={type} onChange={event=>setMotorType(event.target.value as MotorType)}>{(mode === 'HP lookup' ? lookupTypes : [...lookupTypes,'dc']).map(item=><option key={item} value={item}>{item === 'squirrel-cage' ? 'Squirrel cage' : item === 'wound-rotor' ? 'Wound rotor' : item === 'synchronous' ? 'Synchronous' : 'DC'}</option>)}</select>)}<label className="switch"><input type="checkbox" checked={fuse} onChange={e=>setFuse(e.target.checked)} /><span>Time-delay fuse</span></label></div><ElectricalInputs {...standard}/><button className="run" onClick={()=>onResult(motorSizing({fla:flc,type,fuse,phase,voltage:+voltage,poles:+poles,material:standard.material,terminal:+standard.terminal,insulation:+standard.insulation,ambient:+standard.ambient,ccc:+standard.ccc,lookup:mode === 'HP lookup' ? {horsepower:+hp,tableVoltage:tableMotorVoltage(+voltage)} : undefined}))}>Calculate motor circuit <b>→</b></button></>
}
function HvacForm({ standard, onResult }: { standard: Parameters<typeof ElectricalInputs>[0]; onResult: (result: Result) => void }) { const [mca,setMca]=useState('60'),[mocp,setMocp]=useState('80'),[voltage,setVoltage]=useState('208'),[phase,setPhase]=useState('3'),[poles,setPoles]=useState('3'); return <><div className="input-grid">{field('Nameplate MCA',number(mca,setMca), 'Minimum circuit ampacity')}{field('Nameplate MOCP',number(mocp,setMocp), 'Maximum overcurrent protection')}{field('System voltage',select(voltage,setVoltage,voltages))}{field('Phase',select(phase,setPhase,[1,3]))}{field('Circuit poles',select(poles,setPoles,[1,2,3]))}</div><ElectricalInputs {...standard}/><button className="run" onClick={()=>onResult(hvacSizing(+mca,+mocp,standard.material,+standard.terminal,+standard.insulation,+standard.ambient,+standard.ccc,+voltage,+phase as 1|3,+poles))}>Calculate HVAC circuit <b>→</b></button></> }
function GroundForm({ onResult }: { onResult: (result: Result) => void }) {
  const [ocpd,setOcpd]=useState('225'),[material,setMaterial]=useState<Material>('copper'),[ratio,setRatio]=useState('1'),[circuitSize,setCircuitSize]=useState('')
  return <><div className="input-grid">{field('Upstream OCPD',select(ocpd,setOcpd,[15,20,30,60,100,200,225,300,400,450,500,600,800,1000,1200,1600,2000,2500,3000,4000,5000,6000]))}{field('EGC material',select(material,v=>setMaterial(v as Material),materials.map(i=>i.value)))}{field('Vdrop upsize multiplier',number(ratio,setRatio,1), '1 = no intentional conductor upsizing')}{field('Actual circuit conductor',<select value={circuitSize} onChange={event=>setCircuitSize(event.target.value)}><option value="">Not entered</option>{groundingConductorSizes.map(size=><option key={size} value={size}>{size}</option>)}</select>, 'Caps EGC at supplying-conductor area')}</div><button className="run" onClick={()=>onResult(egcSizing(+ocpd,material,+ratio,circuitSize || undefined))}>Calculate EGC <b>→</b></button></>
}
function GecForm({ onResult }: { onResult: (result: Result) => void }) {
  const [sourceMaterial,setSourceMaterial]=useState<Material>('copper'),[sourceSize,setSourceSize]=useState('500'),[sets,setSets]=useState('1'),[material,setMaterial]=useState<Material>('copper'),[electrode,setElectrode]=useState<Electrode>('water-pipe'),[continues,setContinues]=useState(false),[ringSize,setRingSize]=useState('2')
  const electrodes: { value: Electrode; label: string }[] = [{value:'water-pipe',label:'Metal water pipe'},{value:'structural-steel',label:'Structural steel'},{value:'rod-pipe-plate',label:'Rod, pipe, or plate'},{value:'concrete-encased',label:'Concrete-encased electrode'},{value:'ground-ring',label:'Ground ring'}]
  return <><div className="input-grid">{field('Largest ungrounded conductor',select(sourceSize,setSourceSize,groundingConductorSizes))}{field('Ungrounded material',select(sourceMaterial,value=>setSourceMaterial(value as Material),materials.map(item=>item.value)))}{field('Parallel sets per phase',number(sets,setSets,1,1))}{field('GEC material',select(material,value=>setMaterial(value as Material),materials.map(item=>item.value)))}{field('Electrode type',<select value={electrode} onChange={event=>setElectrode(event.target.value as Electrode)}>{electrodes.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select>)}{electrode === 'ground-ring' && field('Ground-ring conductor',select(ringSize,setRingSize,groundingConductorSizes))}<label className="switch"><input type="checkbox" checked={continues} onChange={event=>setContinues(event.target.checked)} /><span>Connection continues to another electrode</span></label></div><button className="run" onClick={()=>onResult(gecSizing({sourceMaterial,sourceSize,parallelSets:+sets,material,electrode,continues,ringSize:electrode === 'ground-ring' ? ringSize : undefined}))}>Calculate GEC <b>→</b></button></>
}
function BusbarForm({ onResult }: { onResult: (result: Result) => void }) {
  const [amps,setAmps]=useState('600'),[continuous,setContinuous]=useState(true),[material,setMaterial]=useState<Material>('copper'),[bars,setBars]=useState('1')
  return <><div className="input-grid">{field('Load current',number(amps,setAmps), 'Amperes')}<label className="switch checkbox-field"><input type="checkbox" checked={continuous} onChange={event=>setContinuous(event.target.checked)} /><span>Continuous load</span></label>{field('Busbar material',select(material,value=>setMaterial(value as Material),materials.map(item=>item.value)))}{field('Parallel bars per phase',select(bars,setBars,[1,2,3,4]))}</div><button className="run" onClick={()=>onResult(busbarSizing({amps:+amps,continuous,material,parallelBars:+bars}))}>Calculate busbar <b>→</b></button></>
}
function ConduitForm({ onResult }: { onResult: (result: Result) => void }) {
  const [raceway,setRaceway]=useState('EMT'),[sets,setSets]=useState([{size:'3/0',quantity:'4'}])
  const setValue = (index: number, key: 'size' | 'quantity', value: string) => setSets(current => current.map((item,itemIndex) => itemIndex === index ? {...item,[key]:value} : item))
  return <>{field('Raceway',select(raceway,setRaceway,['EMT','PVC Sch 40','PVC Sch 80','RMC','IMC']))}<div className="conductor-sets">{sets.map((item,index)=>{ const label = String.fromCharCode(65 + index); return <div className="input-grid conductor-set" key={label}>{field(`Conductor set ${label}`,select(item.size,value=>setValue(index,'size',value),conductors.map(conductor=>conductor.size)))}{field(`Set ${label} quantity`,number(item.quantity,value=>setValue(index,'quantity',value),0,1))}</div> })}</div><div className="conduit-actions"><button type="button" onClick={()=>setSets(current=>current.length < 5 ? [...current,{size:'6',quantity:'1'}] : current)} disabled={sets.length === 5}>Add conductor set</button><button type="button" onClick={()=>setSets(current=>current.length > 1 ? current.slice(0,-1) : current)} disabled={sets.length === 1}>Delete newest set</button></div><button className="run" onClick={()=>onResult(conduitSizing(sets.map(item=>({size:item.size,quantity:+item.quantity})),raceway))}>Calculate conduit fill <b>→</b></button></>
}
function DropForm({ onResult }: { onResult: (result: Result) => void }) { const [amps,setAmps]=useState('60'),[volts,setVolts]=useState('208'),[phase,setPhase]=useState('3'),[length,setLength]=useState('100'),[material,setMaterial]=useState<Material>('copper'),[allowable,setAllowable]=useState('3'); return <><div className="input-grid">{field('Load current',number(amps,setAmps), 'Amperes')}{field('System voltage',select(volts,setVolts,voltages))}{field('Phase',select(phase,setPhase,[1,3]))}{field('One-way length',number(length,setLength), 'Feet')}{field('Material',select(material,v=>setMaterial(v as Material),materials.map(i=>i.value)))}{field('Allowable drop',number(allowable,setAllowable), 'Percent')}</div><button className="run" onClick={()=>onResult(voltageDrop({amps:+amps,volts:+volts,phase:+phase as 1|3,length:+length,material,allowable:+allowable}))}>Check voltage drop <b>→</b></button></> }
function TransformerForm({ onResult }: { onResult: (result: Result) => void }) { const [kva,setKva]=useState('75'),[primary,setPrimary]=useState('480'),[secondary,setSecondary]=useState('208'),[phase,setPhase]=useState('3'); return <><div className="input-grid">{field('Transformer rating',number(kva,setKva), 'kVA')}{field('Primary voltage',select(primary,setPrimary,voltages))}{field('Secondary voltage',select(secondary,setSecondary,voltages))}{field('Phase',select(phase,setPhase,[1,3]))}</div><button className="run" onClick={()=>onResult(transformerSizing(+kva,+primary,+secondary,+phase as 1|3))}>Calculate transformer values <b>→</b></button></> }
function LoadForm({ onResult }: { onResult: (result: Result) => void }) { const [amount,setAmount]=useState('3000'),[unit,setUnit]=useState<'W'|'VA'|'kVA'>('W'),[volts,setVolts]=useState('120'),[phase,setPhase]=useState('1'); return <><div className="input-grid">{field('Load',number(amount,setAmount), 'Enter the nameplate value')}{field('Unit',select(unit,v=>setUnit(v as 'W'|'VA'|'kVA'),['W','VA','kVA']))}{field('Voltage',select(volts,setVolts,voltages))}{field('Phase',select(phase,setPhase,[1,3]))}</div><button className="run" onClick={()=>onResult(loadConversion(+amount,unit,+volts,+phase as 1|3))}>Convert load to amps <b>→</b></button></> }
function PowerFactorForm({ onResult }: { onResult: (result: Result) => void }) { const [kw,setKw]=useState('100'),[existingPf,setExistingPf]=useState('0.80'),[targetPf,setTargetPf]=useState('0.95'); return <><div className="input-grid">{field('Real load',number(kw,setKw), 'kW')}{field('Present PF',number(existingPf,setExistingPf,.01,.01), 'Lagging power factor')}{field('Target PF',number(targetPf,setTargetPf,.01,.01), 'Target lagging power factor')}</div><button className="run" onClick={()=>onResult(powerFactorCorrection({kw:+kw,existingPf:+existingPf,targetPf:+targetPf}))}>Calculate correction <b>→</b></button></> }
function LightingForm({ onResult }: { onResult: (result: Result) => void }) { const [occupancy,setOccupancy]=useState<LightingOccupancy>('office-general'),[area,setArea]=useState('1000'),[unit,setUnit]=useState<'ft²'|'m²'>('ft²'),[lumens,setLumens]=useState('10000'),[cu,setCu]=useState('0.70'),[llf,setLlf]=useState('0.85'); return <><div className="input-grid">{field('Occupancy',<select value={occupancy} onChange={event=>setOccupancy(event.target.value as LightingOccupancy)}>{lightingOccupancies.map(item=><option key={item.id} value={item.id}>{item.label} · {item.footcandles} fc</option>)}</select>)}{field('Room area',number(area,setArea), unit)}{field('Area unit',select(unit,value=>setUnit(value as 'ft²'|'m²'),['ft²','m²']))}{field('Luminaire output',number(lumens,setLumens), 'Lumens per luminaire')}{field('Coefficient of utilization',number(cu,setCu,0,.01), 'Optional · typical 0.70')}{field('Light loss factor',number(llf,setLlf,0,.01), 'Optional · LED typical 0.85')}</div><button className="run" onClick={()=>onResult(lightingSizing({occupancy,area:+area,unit,lumens:+lumens,cu:+cu,llf:+llf}))}>Estimate luminaires <b>→</b></button></> }
function LightingSystemForm({ onResult }: { onResult: (result: Result) => void }) { const [occupancy,setOccupancy]=useState<LightingOccupancy>('office-general'),[area,setArea]=useState('1000'),[unit,setUnit]=useState<LightingUnit>('Imperial'),[lumens,setLumens]=useState('10000'),[cu,setCu]=useState('0.70'),[llf,setLlf]=useState('0.85'); const areaUnit = unit === 'Metric' ? 'm²' : 'ft²'; return <><div className="input-grid">{field('Unit',select(unit,value=>setUnit(value as LightingUnit),['Imperial','Metric']))}{field('Occupancy',<select value={occupancy} onChange={event=>setOccupancy(event.target.value as LightingOccupancy)}>{lightingOccupancies.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select>)}{field('Room area',number(area,setArea), areaUnit)}{field('Luminaire output',number(lumens,setLumens), 'lm per luminaire')}{field('Coefficient of utilization',number(cu,setCu,0,.01), 'Optional · typical 0.70')}{field('Light loss factor',number(llf,setLlf,0,.01), 'Optional · LED typical 0.85')}</div><button className="run" onClick={()=>onResult(lightingSizingBySystem({occupancy,area:+area,unit,lumens:+lumens,cu:+cu,llf:+llf}))}>Estimate luminaires <b>→</b></button></> }

function TablesPage() {
  const [selected,setSelected] = useState<string | null>(null)
  const table = referenceTables.find(item => item.id === selected)
  if (table) return <section className="table-page"><button className="back-table" onClick={()=>setSelected(null)}>← All NEC tables</button><p className="eyebrow">{table.code}</p><h2>{table.title}</h2><p>{table.description}</p><div className="table-scroll"><table><thead><tr>{table.headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{table.rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>{table.notes?.map(note=><p className="table-note" key={note}>{note}</p>)}</section>
  return <section className="table-page"><p className="eyebrow">2023 NEC BASELINE</p><h2>Field reference</h2><p>Choose a table for a focused, scrollable reference view.</p><div className="table-list">{referenceTables.map(table=><button key={table.id} onClick={()=>setSelected(table.id)}><span>{table.code}</span><b>{table.title}</b><small>{table.description}</small></button>)}</div></section>
}

function CompleteTablesPage() {
  const [selected,setSelected] = useState<string | null>(null)
  const table = referenceTables.find(item => item.id === selected)
  if (table) return <section className="table-page"><button className="back-table" onClick={()=>setSelected(null)}>All NEC tables</button><p className="eyebrow">{table.code}</p><h2>{table.title}</h2><p>{table.description}</p>{table.sections.map((section,index)=><section className="table-section" key={section.title ?? index}>{section.title && <h3>{section.title}</h3>}<div className="table-scroll"><table><thead><tr>{section.headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{section.rows.map((row,rowIndex)=><tr key={rowIndex}>{row.map((value,cellIndex)=><td key={cellIndex}>{value}</td>)}</tr>)}</tbody></table></div>{section.notes?.map(note=><p className="table-note" key={note}>{note}</p>)}</section>)}{table.notes?.map(note=><p className="table-note" key={note}>{note}</p>)}</section>
  return <section className="table-page"><p className="eyebrow">2023 NEC BASELINE</p><h2>Field reference</h2><p>Choose a table for a focused, scrollable reference view.</p><div className="table-list">{referenceTables.map(table=><button key={table.id} onClick={()=>setSelected(table.id)}><span>{table.code}</span><b>{table.title}</b><small>{table.description}</small></button>)}</div></section>
}

function NecTablesPage() {
  const [selected,setSelected] = useState<string | null>(null)
  const table = referenceTables.find(item => item.id === selected)
  if (table) return <section className="table-page"><button className="back-table" onClick={()=>setSelected(null)}>All NEC tables</button><p className="eyebrow">{table.code}</p><h2>{table.title}</h2>{table.sections.map((section,index)=><section className="table-section" key={section.title ?? index}>{section.title && <h3>{section.title}</h3>}<div className="table-scroll"><table><thead><tr>{section.headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{section.rows.map((row,rowIndex)=><tr key={rowIndex}>{row.map((value,cellIndex)=><td key={cellIndex}>{value}</td>)}</tr>)}</tbody></table></div>{section.notes?.map(note=><p className="table-note" key={note}>{note}</p>)}</section>)}{table.notes?.map(note=><p className="table-note" key={note}>{note}</p>)}</section>
  return <section className="table-page"><h2>NEC tables</h2><div className="table-list">{referenceTables.map(table=><button key={table.id} onClick={()=>setSelected(table.id)}><span>{table.code}</span><b>{table.title}</b></button>)}</div></section>
}

export default function App() {
  const [active, setActive] = useState<Tool>('general'); const [open, setOpen] = useState(false); const [result, setResult] = useState<Result | null>(null); const [recent, setRecent] = useState<Result[]>([])
  useEffect(() => { const saved = localStorage.getItem('micronec-recents'); if (saved) setRecent(JSON.parse(saved)) }, [])
  const save = (next: Result) => { setResult(next); setRecent(current => { const updated = [next, ...current.filter(item => item.primary !== next.primary)].slice(0, 6); localStorage.setItem('micronec-recents', JSON.stringify(updated)); return updated }) }
  const choose = (id: Tool) => { setActive(id); setResult(null); setOpen(false) }
  const groups = [...new Set(tools.map(item => item.group))]
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><img src="/applogo.png" alt="MicroNEC" /><div><strong>MicroNEC</strong><small>FIELD CALCULATOR</small></div><button className="close" onClick={()=>setOpen(false)}>×</button></div><nav>{groups.map(group => <div className="nav-group" key={group}><p>{group}</p>{tools.filter(item=>item.group===group).map(item=><button key={item.id} className={active===item.id?'active':''} onClick={()=>choose(item.id)}><em>{item.mark}</em>{item.label}</button>)}</div>)}</nav><div className="side-foot"><span>2023 NEC baseline</span><span>Local data only</span></div></aside><main><header><button className="menu" onClick={()=>setOpen(true)} aria-label="Open calculators">☰</button><div><h1>{titles[active][0]}</h1></div><div className="edition">NEC <b>2023</b></div></header>{active === 'tables' ? <NecTablesPage/> : <><div className="workspace"><section className="form-card"><p>{titles[active][1]}</p><Calculator active={active} onResult={save}/></section><ResultCard result={result}/></div>{recent.length > 0 && <section className="recents"><div><p className="eyebrow">ON THIS DEVICE</p><h2>Recent checks</h2></div><button onClick={()=>{localStorage.removeItem('micronec-recents');setRecent([])}}>Clear history</button><div className="recent-list">{recent.map((item,index)=><button key={`${item.primary}-${index}`} onClick={()=>setResult(item)}><span>{item.title}</span><b>{item.primary}</b></button>)}</div></section>}</>}</main><div className={open?'scrim show':'scrim'} onClick={()=>setOpen(false)} /></div>
}
